### ISSUE TITLE
Batch meta-transaction

### ISSUE THREAD

**Issue by Amxx** [Amxx/GMTX#2]
- [ ] Create a GMTXBatch Object
- [ ] Add ERC712 support for this GMTXBatch Object
- [ ] Add a `processMetaTxBatch` method that process all transactions sequencially (or reverts all)

Remarks:
- One single signature for the batch prevents transactions from being played individually.
- Nonce/expiry of all transaction should be compatible. I would recommend putting the restriction on the first meta-tx of the batch and then not including any restriction on the following ones.
- We must be carrefull `with msg.value`

**Comment by Amxx** [comment]
Started an implementation: https://github.com/Amxx/GMTX/commit/62131d4c7bd4fa5ece43c93e9feeae4f70fa2f65

**Comment by Amxx** [comment]
Cleaner separation of txs / parameters: https://github.com/Amxx/GMTX/commit/25c554b8ff91de85c4bf8ec6825c365dd994823d#diff-52017cb31f8e72865e8814f9fd38ab7a
